import { StyleSheet } from 'react-native';
import { COLORS, Fonts } from '@nightlight/src/global.styles';

export default StyleSheet.create({
  container: {
    backgroundColor: COLORS.NIGHTLIGHT_BLACK,
    height: '100%',
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  emailContainer: {
    backgroundColor: 'none',
    width: '90%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  emailInput: {
    fontSize: 16,
    padding: 15,
    marginLeft: 30,
    marginRight: 30,
    marginTop: 10,
    marginBottom: 10,
    borderRadius: 10,
    backgroundColor: COLORS.WHITE,
    fontFamily: Fonts.COMFORTAA_REGULAR,
    maxWidth: 350,
    width: '90%',
  },
  passwordContainer: {
    width: '90%',
    flexDirection: 'row',
    borderColor: '#e3e3e3',
    borderRadius: 10,
    marginLeft: 30,
    marginRight: 30,
    marginTop: 10,
    marginBottom: 10,
    backgroundColor: COLORS.WHITE,
    maxWidth: 350,
    alignItems: 'center',
  },
  passwordInput: {
    fontFamily: Fonts.COMFORTAA_REGULAR,
    fontSize: 16,
    padding: 15,
    paddingRight: 50,
    width: '100%',
  },
  viewPasswordButton: {
    marginRight: 10,
    position: 'absolute',
    right: 10,
  },
  forgotPasswordContainer: {
    alignItems: 'flex-end',
    justifyContent: 'flex-end',
    width: '90%',
    maxWidth: 350,
    marginRight: 30,
    marginLeft: 30,
    paddingLeft: 15,
    paddingRight: 15,
    paddingBottom: 20,
  },
  forgotPassword: {
    color: COLORS.GRAY,
    textDecorationLine: 'underline',
  },
  logoDot: {
    height: 100,
    width: 100,
    backgroundColor: COLORS.NIGHTLIGHT_BLUE,
    borderRadius: 50,
    margin: 10,
    shadowColor: COLORS.NIGHTLIGHT_BLUE,
    shadowRadius: 20,
    shadowOpacity: 10,
    shadowOffset: {
      width: 0,
      height: 0,
    },
  },
  logoBody: {
    height: 100,
    width: 100,
    borderTopRightRadius: 50,
    borderTopLeftRadius: 50,
    backgroundColor: COLORS.WHITE,
    marginBottom: 15,
  },
  signInButton: {
    backgroundColor: COLORS.NIGHTLIGHT_BLUE,
    borderRadius: 10,
    width: '90%',
    maxWidth: 350,
    marginLeft: 30,
    marginRight: 30,
    marginTop: 10,
    marginBottom: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  signInButtonText: {
    fontFamily: Fonts.COMFORTAA_REGULAR,
    fontSize: 16,
    color: COLORS.WHITE,
    padding: 15,
  },
  continueWithText: {
    fontFamily: Fonts.COMFORTAA_BOLD,
    fontSize: 12,
    color: COLORS.GRAY,
    padding: 5,
  },
  googleSignInButton: {
    backgroundColor: COLORS.WHITE,
    borderRadius: 10,
    width: '90%',
    maxWidth: 350,
    marginLeft: 30,
    marginRight: 30,
    marginTop: 10,
    marginBottom: 10,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
  },
  googleSignInButtonText: {
    color: COLORS.GRAY,
    padding: 15,
    fontSize: 16,
    fontFamily: Fonts.ROBOTO_REGULAR,
    fontWeight: '400',
  },
  googleIcon: {
    width: 20,
    height: 20,
  },
  notMemberText: {
    fontFamily: Fonts.COMFORTAA_REGULAR,
    color: COLORS.WHITE,
    marginBottom: 100,
  },
  notMemberLink: {
    color: COLORS.NIGHTLIGHT_BLUE,
    textDecorationLine: 'underline',
  },
});
