import { StyleSheet } from 'react-native';
import { COLORS, Fonts } from '@nightlight/src/global.styles';
import {
  DEVICE_HEIGHT,
  DEVICE_WIDTH,
  EMERGENCY_BUTTON_RADIUS,
  NAVBAR_HEIGHT,
} from '@nightlight/src/constants';

export default StyleSheet.create({
  container: {
    backgroundColor: COLORS.NIGHTLIGHT_GRAY,
    height: DEVICE_HEIGHT,
  },
  contentContainer: {
    flex: 1,
    paddingHorizontal: 10,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerButton: {
    padding: 10,
  },
  title: {
    fontFamily: Fonts.COMFORTAA_BOLD,
    fontSize: 24,
    color: COLORS.WHITE,
    marginVertical: 10,
    textAlign: 'center',
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 10,
  },
  sectionHeaderTitle: {
    fontFamily: Fonts.COMFORTAA_BOLD,
    fontSize: 16,
  },
  friendsSectionTitle: {
    color: COLORS.GRAY,
  },
  sectionHeaderCountContainer: {
    marginLeft: 5,
    borderRadius: 10,
    height: 20,
    minWidth: 20,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 5,
  },
  friendsCountContainer: {
    backgroundColor: COLORS.GRAY,
  },
  sectionHeaderCount: {
    textAlign: 'center',
    color: COLORS.WHITE,
  },
  friendsList: {},
  contactSeparator: {
    height: 2,
  },

  rowView: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  activeGroupText: {
    alignSelf: 'flex-start',
    marginLeft: '6%',
    fontFamily: Fonts.COMFORTAA_BOLD,
    fontSize: 16,
    color: COLORS.GREEN,
    textShadowColor: COLORS.NIGHTLIGHT_BLACK,
    textShadowOffset: { width: 0, height: 4 },
    textShadowRadius: 4,
    paddingTop: 5,
  },
  activeBox: {
    width: '90%',
    // borderColor: COLORS.GREEN,
    borderRadius: 10,
    // borderWidth: 2,
    marginTop: 5,
    alignSelf: 'center',
    // shadowColor: COLORS.GREEN,
    // shadowOffset: { width: 0, height: 0 },
    // shadowRadius: 10,
    // shadowOpacity: 0.5,
  },
  glow: {
    position: 'absolute',
    height: '100%',
    width: '100%',
    borderColor: COLORS.GREEN,
    borderWidth: 2,
    shadowColor: COLORS.GREEN,
    shadowOffset: { width: 0, height: 0 },
    shadowRadius: 10,
    shadowOpacity: 0.75,
    borderRadius: 10,
  },
  allFriendsText: {
    marginLeft: '6%',
    fontFamily: Fonts.COMFORTAA_BOLD,
    fontSize: 16,
    color: COLORS.GRAY,
    textShadowColor: COLORS.NIGHTLIGHT_BLACK,
    textShadowOffset: { width: 0, height: 4 },
    textShadowRadius: 4,
    paddingTop: 10,
    paddingBottom: 10,
  },
  friendBox: {
    alignSelf: 'center',
    width: '90%',
    borderColor: COLORS.NIGHTLIGHT_BLACK,
    borderRadius: 10,
    borderWidth: 1,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 4,
  },
  greenCircle: {
    width: 20,
    height: 20,
    borderRadius: DEVICE_WIDTH / 2,
    backgroundColor: COLORS.GREEN,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 5,
  },
  grayCircle: {
    width: 20,
    height: 20,
    borderRadius: DEVICE_WIDTH / 2,
    backgroundColor: COLORS.GRAY,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 5,
  },
  numberText: {
    fontFamily: Fonts.COMFORTAA_REGULAR,
    fontSize: 14,
    color: COLORS.WHITE,
  },
  emptyAvailableUsersText: {
    color: COLORS.GRAY,
    fontFamily: Fonts.COMFORTAA_BOLD,
    fontSize: 14,
    textAlign: 'center',
    marginTop: 20,
    marginBottom: 15,
    marginHorizontal: 50,
    lineHeight: 18,
  },
});
