name: Format code with Prettier and run tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  format:
    name: Format code with Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install packages
        run: npm ci
      - name: Run formatter
        run: npm run format
      - uses: stefanzweifel/git-auto-commit-action@v4.16.0
        with:
          commit_message: Apply Prettier formatting
  unit-test:
    name: Run jest tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install packages
        run: npm ci
      - name: Run tests
        run: npm test -- --testPathPattern=__tests__
    env:
      FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
      FIREBASE_AUTHDOMAIN: ${{ secrets.FIREBASE_AUTHDOMAIN }}
      FIREBASE_PROJECTID: ${{ secrets.FIREBASE_PROJECTID }}
      FIREBASE_STORAGEBUCKET: ${{ secrets.FIREBASE_STORAGEBUCKET }}
      FIREBASE_MESSAGINGSENDERID: ${{ secrets.FIREBASE_MESSAGINGSENDERID }}
      FIREBASE_APPID: ${{ secrets.FIREBASE_APPID }}
      FIREBASE_MEASUREMENTID: ${{ secrets.FIREBASE_MEASUREMENTID }}
      MAPBOX_API_KEY: ${{ secrets.MAPBOX_API_KEY }}
      SERVER_URL: ${{ secrets.SERVER_URL }}
  e2e-test:
    name: Run Detox e2e tests
    runs-on: macos-latest
    timeout-minutes: 120
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Node
        uses: actions/setup-node@v3
      - name: Cache node modules
        uses: actions/cache@v3
        id: cache
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Rebuild detox
        if: steps.cache.outputs.cache-hit == 'true'
        run: npx detox clean-framework-cache && detox build-framework-cache
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Cache Pods
        uses: actions/cache@v1
        id: podcache
        with:
          path: ios/Pods
          key: pods-${{ hashFiles('**/Podfile.lock') }}

      - name: Update Pods
        run: |
          gem update cocoapods xcodeproj
          cd ios && pod install && cd ..
      - run: brew tap wix/brew
      - run: brew install applesimutils
      - run: npx detox build e2e --configuration ios.sim.release
      - run: npx detox test e2e --configuration ios.sim.release --cleanup --debug-synchronization 200
